apiVersion: v1
kind: ConfigMap
metadata:
  name: ssm-config
data:
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "duty_db"
  DB_USER: "duty_user"
  MQ_URL: "amqp://rabbitmq-service:5672"
  MINIO_ENDPOINT: "http://minio-service:9000"
  MINIO_BUCKET: "roster-images"
