apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ssm-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ssm.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ssm-api
            port:
              number: 80
