apiVersion: v1
kind: Secret
metadata:
  name: ssm-secret
type: Opaque
stringData:
  DB_PASSWORD: "duty_pass"
  JWT_SECRET: "change-this-in-production"
  MINIO_ACCESS_KEY: "minio"
  MINIO_SECRET_KEY: "miniopass"
